### ISSUE TITLE
Weird font misrendering in PDF

### ISSUE THREAD

**Issue by jswalden** [mozilla/pdf.js#10544]
Attach (recommended) or Link to PDF file here: [pet.pdf](https://github.com/mozilla/pdf.js/files/2852697/pet.pdf)

Configuration:
- Web browser and its version: Firefox nightly
- Operating system and its version: Fedora 28
- PDF.js version: tip
- Is a browser extension: testing using `gulp server` and picking the file off the local file system

Steps to reproduce the problem:
1. Load the PDF!

What is the expected behavior? 
![screenshot from 2019-02-11 11-31-09](https://user-images.githubusercontent.com/4139753/52588101-8fd4ce00-2df0-11e9-9fc3-0e0b14e63b0c.png)

What went wrong?
![screenshot from 2019-02-11 11-30-48](https://user-images.githubusercontent.com/4139753/52588120-9bc09000-2df0-11e9-853a-c16181fab20c.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

@arai-a notes on IRC that there are some possibly potentially likely relevant console warnings:

> PDF 2dbe539840cea24147791d677c5928ba [1.4 Nuance PDF Create 8 / Microsoft Word - Davis petition 10.18.docx] (PDF.js: -) app.js:1084:6
> Warning: Failed to load font "g_d1_f1": SyntaxError: An invalid or illegal string was specified util.js:306:4
> Warning: Failed to load font "g_d1_f3": SyntaxError: An invalid or illegal string was specified util.js:306:4
> Warning: Failed to load font "g_d1_f4": SyntaxError: An invalid or illegal string was specified util.js:306:4

Could be, for all I know, that the PDF itself is not quite up to snuff and all.  Yet evince views it correctly and someone thought the PDF actually worked correctly enough to submit it to the United States Supreme Court with serious legal consequences if it didn't work correctly, so... ¯\\\_(ツ)_/¯

**Comment by calixteman** [comment]
This is fixed now.

**Comment by Snuffleupagus** [comment]
> This is fixed now.

No it's really not fixed, since the *underlying* bug is still present. What landed in PR #10539 is merely a work-around, since the fonts still are rejected by the sanitizer, note the console output:
```
PDF 2dbe539840cea24147791d677c5928ba [1.4 Nuance PDF Create 8 / Microsoft Word - Davis petition 10.18.docx] (PDF.js: 2.9.273) viewer.js:1501:13
downloadable font: CFF: Undefined operator: 0 (0x0) (font-family: "g_d0_f1" style:normal weight:400 stretch:100 src index:0) source: (invalid URI)
downloadable font: CFF : Failed validating CharStrings INDEX (font-family: "g_d0_f1" style:normal weight:400 stretch:100 src index:0) source: (invalid URI)
downloadable font: CFF : Failed to parse table (font-family: "g_d0_f1" style:normal weight:400 stretch:100 src index:0) source: (invalid URI)
downloadable font: rejected by sanitizer (font-family: "g_d0_f1" style:normal weight:400 stretch:100 src index:0) source: (invalid URI)
downloadable font: font load failed (font-family: "g_d0_f1" style:normal weight:400 stretch:100 src index:0) source: (invalid URI)
Warning: Failed to load font 'g_d0_f1': 'SyntaxError: An invalid or illegal string was specified'. pdf.js:973:13
Warning: Failed to load font 'g_d0_f3': 'SyntaxError: An invalid or illegal string was specified'. pdf.js:973:13
downloadable font: CFF: Undefined operator: 0 (0x0) (font-family: "g_d0_f3" style:normal weight:400 stretch:100 src index:0) source: (invalid URI)
downloadable font: CFF : Failed validating CharStrings INDEX (font-family: "g_d0_f3" style:normal weight:400 stretch:100 src index:0) source: (invalid URI)
downloadable font: CFF : Failed to parse table (font-family: "g_d0_f3" style:normal weight:400 stretch:100 src index:0) source: (invalid URI)
downloadable font: rejected by sanitizer (font-family: "g_d0_f3" style:normal weight:400 stretch:100 src index:0) source: (invalid URI)
downloadable font: font load failed (font-family: "g_d0_f3" style:normal weight:400 stretch:100 src index:0) source: (invalid URI)
downloadable font: CFF: Undefined operator: 0 (0x0) (font-family: "g_d0_f4" style:normal weight:400 stretch:100 src index:0) source: (invalid URI)
downloadable font: CFF : Failed validating CharStrings INDEX (font-family: "g_d0_f4" style:normal weight:400 stretch:100 src index:0) source: (invalid URI)
downloadable font: CFF : Failed to parse table (font-family: "g_d0_f4" style:normal weight:400 stretch:100 src index:0) source: (invalid URI)
downloadable font: rejected by sanitizer (font-family: "g_d0_f4" style:normal weight:400 stretch:100 src index:0) source: (invalid URI)
downloadable font: font load failed (font-family: "g_d0_f4" style:normal weight:400 stretch:100 src index:0) source: (invalid URI)
Warning: Failed to load font 'g_d0_f4': 'SyntaxError: An invalid or illegal string was specified'. pdf.js:973:13
```

**Comment by calixteman** [comment]
And I think I've a fix.
