### ISSUE TITLE
No spaces between words when copying text

### ISSUE THREAD

**Issue by mrtcode** [mozilla/pdf.js#10640]
PDF files:
[1.pdf](https://github.com/mozilla/pdf.js/files/2955999/1.pdf)
[2.pdf](https://github.com/mozilla/pdf.js/files/2956000/2.pdf)
[3.pdf](https://github.com/mozilla/pdf.js/files/2956002/3.pdf)

Configuration:
- Web browser and its version: Chrome, Firefox
- Operating system and its version: Ubuntu, macOS
- PDF.js version: 2.2.42, but the same was with 2.1.x, and with https://mozilla.github.io/pdf.js/web/viewer.html
- Is a browser extension: no

Steps to reproduce the problem:
1. Select text
2. Copy text

What went wrong?

Getting this:
`OpenSansisahumanistsansseriftypefacedesignedbySteveMatteson.OpenSanswasdesignedwithanuprightstress,openformsandaneu-tral,yetfriendlyappearance.Itwasoptimizedforprint,web,andmobileinterfaces,andhasexcellentlegibilitycharacteristicsinitsletterforms(seefigureonthefollowingpage).ThisfontisavailablefromtheGoogleFontDirectory[]asTrueTypefileslicensedundertheApacheLicenseversion..`

Instead of this:
`Open Sans is a humanist sans serif typeface designed by Steve Matteson.
Open Sans was designed with an upright stress, open forms and a neutral,
yet friendly appearance. It was optimized for print, web, and mobile
interfaces, and has excellent legibility characteristics in its letterforms (see
figure 1 on the following page). This font is available from the Google Font
Directory [1] as TrueType files licensed under the Apache License version 2.0.`

This is quite significant problem, because I would say 1/20 of scientific papers encounter this problem.

**Comment by ocaioaugusto** [comment]
Can you check it again? It looks it was already solved

**Comment by ocaioaugusto** [comment]
It is still happening to you? I tested here and i coundt see this bug

**Comment by mrtcode** [comment]
Yeah, the problem still exists. Just try to open the attached `1.pdf` in https://mozilla.github.io/pdf.js/web/viewer.html and copy -> paste text. I tried out with the current master on Chrome on both Ubuntu and Android. I think it should be the same whatever system you would use.

**Comment by dhyanaswain** [comment]
Hi,
I am facing the same issue 
Any update on this.

**Comment by elatedstar** [comment]
Space between words is removed for paragraphs with style="text-align: justify;"
each word is rendered in separate span. When i copied text from pdf to notepad spaces are removed. 
It works fine without this style. 
We are converting html from ckeditor to pdf, user expect pdf renders exactly same ways as it shown in ckeditor(WYSIWYG). I tried pdfjs-2.1.266-dist, problem is consistent. Please help.

**Comment by CristiTr** [comment]
Still facing this issue.
Any updates/ workarounds on this ?

**Comment by KnIfER** [comment]
Need to say that this issue exits right in the default viewer.
There's no space between lines and 
![Screenshot (176)](https://user-images.githubusercontent.com/11593903/69637457-a3a5a400-1093-11ea-8eed-ca84e3ff76d5.png)
is pasted as `the systemidentifieshot(`

**Comment by KnIfER** [comment]
how do chrome and acrobat handle this?

**Comment by kfir91** [comment]
Any solution for that?

**Comment by immanuelfodor** [comment]
I need to open some PDFs in Okular (Linux) that copies the text just fine that is missing spaces in Firefox :(

**Comment by jg3** [comment]
Running 76.0.1 (64-bit) on Mac OS and it happens still.  Download the PDF and open it in Preview and copy-paste includes spaces, as expected.

**Comment by yuvilio** [comment]
Possible hotfix that _may_ help here https://github.com/mozilla/pdf.js/issues/7310#issuecomment-530713483 ? YMMV

**Comment by FredBonux** [comment]
I think I've found an issue in core/evaluator.js:2043-2056.
```js
if (spaceWidth) {
        textContentItem.spaceWidth = spaceWidth;
        textContentItem.fakeSpaceMin = spaceWidth * SPACE_FACTOR;
        textContentItem.fakeMultiSpaceMin = spaceWidth * MULTI_SPACE_FACTOR;
        textContentItem.fakeMultiSpaceMax = spaceWidth * MULTI_SPACE_FACTOR_MAX;
        // It's okay for monospace fonts to fake as much space as needed.
        textContentItem.textRunBreakAllowed = !font.isMonospace;
} else {
        textContentItem.spaceWidth = 0;
        textContentItem.fakeSpaceMin = Infinity;
        textContentItem.fakeMultiSpaceMin = Infinity;
        textContentItem.fakeMultiSpaceMax = 0;
        textContentItem.textRunBreakAllowed = false;
}
```
This if-else is not correct I think, the spaceWidth should be always grater than zero by definition, setting a fallback value equals to the min width of the current font solves the issue for the test pdf.

The fix that worked for me:
```js
var fontMinWidth = Math.min.apply(null, font.widths.filter(w => !!w));
var spaceWidth = (fontMinWidth / 1000) * textState.fontSize;
```

**Comment by BartusZak** [comment]
Facing similar issue:

![image](https://user-images.githubusercontent.com/16143176/99371778-a52d3500-28bf-11eb-8022-50de7491d061.png)


```
{
      str: 'wykonanaprzezBibliotekęNarodowązegzemplarzapochodzącegozezbiorówBN.',
      dir: 'ltr',
      width: 250.77697646469932,
      height: 8.012811977655979,
      transform: [Array],
      fontName: 'g_d0_f1'
    },
```

any ideas?

**Comment by lbittner-pdftron** [comment]
I am able to reproduce this issue as well on multiple documents.

@FredBonux solution above mostly solves the problem, but there are still a few scenarios where some words in the copied text has no spaces.

**Comment by marco-c** [comment]
Could this possibly have been fixed by #13257?

**Comment by Snuffleupagus** [comment]
> Could this possibly have been fixed by #13257?

No, this issue is *still present* in even after that PR.

---

@marco-c Note that you can very easily test this yourself, with the demo viewer (which is basically a PDF.js Nightly build) available at https://mozilla.github.io/pdf.js/web/viewer.html
Download the PDF files above, and then open them with the demo viewer either by:
 - Dragging-and-dropping the PDF file onto the viewer.
 - Clicking on the "Open File"-button on the right-hand side of the viewer toolbar, and select the PDF file.

**Comment by calixteman** [comment]
I had a look at 1.pdf.
First sentence after `Introduction` is using a font (`F66`) where `spaceWidth` is `~1839` and the space between Open and Sans is `265` which is `~14%` of `spaceWidth` so from this point of view it looks like this is a tracking space.
For information a "a" has a width equal to `~1138` when a "A" has `~1294` so it seems that this `spaceWidth` is quite big.
We should base our heuristic on something else that `spaceWidth` (which can be null).

**Comment by calixteman** [comment]
The `spaceWidth` in `F66` is defined through a width table. In the font itself the space width is around `530` which seems to be more realistic. Anyway a white space is a visual thing so its width must base on what we see so we must try to infer a good value from the font itself: with a ttf font we could try to get the width of a " " (or a "i")  from the `hmtx` table or better from the `glyf` table. The problem is how to guess this value without a ttf font or with non latin alphabet (if " " is not in the font).

**Comment by FredBonux** [comment]
My "solution" above was based on this thought:
If the distance is greater than the width of the narrower char of the font, then that distance should be a space.
That's because, usually, the " " is not the narrower char.
But that is based on my "close to none" knowledge on fonts, hope it could help.
