### ISSUE TITLE
MS Edge Beta: Page is rotated when switching between PDF tabs

### ISSUE THREAD

**Issue by quangkieu** [mozilla/pdf.js#11126]
Attach (recommended) or Link to PDF file here:

[PDF Link](http://web.simmons.edu/~gslislab/howto/create-pdfs.pdf)

Configuration:
- Web browser and its version: Microsoft Edge Chromium: 78.0.262.0 (Official build) dev (64-bit)
- Operating system and its version: Windows 10 Pro 1903: 18362.10012
- Browser Extension PDF Viewer version: 2.2.191
- Is a browser extension: $TRUE

Steps to reproduce the problem:
1. Open the any pdf files in 2 tabs
2. Switch tab pdf 1
3. Switch to tab pdf 2
4. Then switch back to pdf 1
5. The pages in view of tab 1 is now rotated
NOT happen when switch to normal browser page

What is the expected behavior? (add screenshot)
The page should be in correct rotation

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/4308312/64463338-ad8dbb80-d0d1-11e9-8cc9-02fdfa7c7e14.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
There's quite frankly no code in the PDF.js default viewer which could explain this behaviour, and it doesn't happen with e.g. the built-in Firefox PDF Viewer, hence this must be a canvas bug in Edge and/or Chromium itself.
This needs to be reported to the Edge/Chromium team instead, since it cannot be fixed here.

**Comment by Shivansh2407** [comment]
Please assign me this issue so that I can Help on this issue.

**Comment by timvandermeij** [comment]
Feel free to debug this, however keep in mind that this could very well be a platform bug, i.e., a bug in Chrome.

**Comment by christian-steinmeyer** [comment]
+1, happens in overleaf pdf view as well.

**Comment by quangkieu** [comment]
seem like new IE Edge fixed this

**Comment by timvandermeij** [comment]
Closing since this should be fixed now and it's not something that PDF.js causes.

**Comment by newsiberian** [comment]
I still face with this in Chromium 78.0.3904.97. Is anyone knows, is there a bug about this at chrome bug tracker exists?
