### ISSUE TITLE
Rendering issue with some objects on Chrome

### ISSUE THREAD

**Issue by vkolova** [mozilla/pdf.js#11918]
Attach (recommended) or Link to PDF file here:
[Test file.pdf](https://github.com/mozilla/pdf.js/files/4656226/Test.file.pdf)

Configuration:
- Web browser and its version: Chrome Version 81.0.4044.138 (Official Build) (64-bit)
- Operating system and its version: Windows 10
- PDF.js version: latest
- Is a browser extension: no

Steps to reproduce the problem:
1. Open [https://mozilla.github.io/pdf.js/web/viewer.html](https://mozilla.github.io/pdf.js/web/viewer.html)
2. Load the provided .pdf file

What is the expected behavior? (add screenshot)
![image](https://user-images.githubusercontent.com/5569382/82438616-02c3fe80-9aa2-11ea-9003-b75ea1e7aac6.png)

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/5569382/82438640-09527600-9aa2-11ea-810b-071da7e37896.png)

**Comment by timvandermeij** [comment]
This looks like a Chrome-specific rendering bug since the file is rendered properly in Firefox 76.0.1 for me.

**Comment by Snuffleupagus** [comment]
Looks OK in Google Chrome 88 now, probably fixed by either PR #12812 and/or #12864.

**Comment by calixteman** [comment]
The bug is still: it depends of the zoom level.
I filed a bug on chrome's side: https://bugs.chromium.org/p/chromium/issues/detail?id=1170396
