### ISSUE TITLE
Filled in text from text area and input-fields don't render properly when printing the PDF

### ISSUE THREAD

**Issue by timonkalke** [mozilla/pdf.js#12883]
PDF File:
[simple_pdf_with_inputs_and_text-area.pdf](https://github.com/mozilla/pdf.js/files/5850413/simple_pdf_with_inputs_and_text-area.pdf)

Configuration:
- Web browser and its version: Firefox 84.0.2 (64-bit)
- Operating system and its version: MacOS Mojave Version 10.14.6
- PDF.js version:
- Is a browser extension: No

Steps to reproduce the problem:
1. Open the PDF in Firefox with the PDF viewer.
2. Fill all the inputs/text areas with random values.
3. Click the print-button in the top right corner.

What is the expected behavior?
The text in the input-fields/text-areas should be displayed in the print preview the same way as it is displayed in the PDF viewer. (Screenshots made with same PDF but opened in Google Chrome)

PDF in Chrome PDF viewer:
<img width="818" alt="image" src="https://user-images.githubusercontent.com/46101300/105375955-82920200-5c09-11eb-9431-640f6423796f.png">

PDF in Chrome print preview:
<img width="1182" alt="image" src="https://user-images.githubusercontent.com/46101300/105376048-9ccbe000-5c09-11eb-9d1e-16a31929d31c.png">

What went wrong?
The text in the input-fields are displayed bigger in the print preview than in the PDF viewer.
The text in the text area is displayed much bigger in the print preview than in the PDF viewer.

PDF in Firefox PDF viewer:
![image](https://user-images.githubusercontent.com/46101300/105377151-cb968600-5c0a-11eb-9aa4-f3c642583710.png)

PDF in Firefox print preview:
![image](https://user-images.githubusercontent.com/46101300/105377241-e10bb000-5c0a-11eb-9f71-b0c4126445aa.png)

**Comment by dhufnagel** [comment]
This is a problem with calculating the auto font-size. The PDF viewer uses the default font-size of 9px, while printing calculates the font-size based on the field height. The latter works for single line fields, as long as the text fits inside the width. For multiline fields this fails as seen in the field description.
Other viewers not only calculate the font-size based on the height (as stated in the pdf spec), but also based on the width. 
There is currently a PR which addresses some points of this issue: https://github.com/mozilla/pdf.js/pull/12759/files#r553646611

But work needs to be done for the viewer part.

**Comment by timonkalke** [comment]
Do you know a workaround for my issue?
I generate the PDF out of an HTML template, so i can change the PDF however i want.

**Comment by dhufnagel** [comment]
You have to set the font-size to a fixed value, e.g. 9px. Then the printout and the preview/input should be the same. If you take another font-size than 9px the viewer will display it wrong. You'll then have to wait till firefox upgrades pdf.js to the master branch version, as this is a feature which was implemented a few days ago.

**Comment by timonkalke** [comment]
This solution worked for the inputs but not for the text area.
I guess I'll have to wait then.

Thanks for your help.

**Comment by dhufnagel** [comment]
Hi, I edited the provided pdf with acrobat and set the font-size of the textarea to 9px and it works as expected. The printed pdf looks the same as the input.
[simple_pdf_with_inputs_and_text-area.pdf](https://github.com/mozilla/pdf.js/files/5868172/simple_pdf_with_inputs_and_text-area.pdf)

**Comment by calixteman** [comment]
Fixed:
https://github.com/mozilla/pdf.js/commit/3f3b01b7106b64f979c539776f7371cb1b3ec3cc
Thank you for reporting.

**Comment by marlonhort** [comment]
This bug is still happening to me, In which release was the fix for it included with?
Please check the gif I attached where we can see it happening.
![Pdfjs bug](https://user-images.githubusercontent.com/29414577/151222101-fed63d39-152f-4a5a-be27-3ef123139341.gif)

**Comment by calixteman** [comment]
You can try in a recent Firefox (the last release is 96) and it'll contain the fix for this bug.
But here, the font guess is based on the field height which is probably a bit high here (in considering what I see on your screencast) and which could explain why it doesn't fit correctly the width.
Could you file a new bug please and I'll have a look asap ?
Thank you.

**Comment by marlonhort** [comment]
I tested it with the latest version of Firefox as well and the same issue is still reproducible:
![Pdfjs bug - latest Firefox](https://user-images.githubusercontent.com/29414577/151243377-1c106070-4999-4fc1-9779-cb5732269d51.gif)

Here's the new bug I filed:
https://github.com/mozilla/pdf.js/issues/14502

Thanks @calixteman!
