### ISSUE TITLE
Rendering font error

### ISSUE THREAD

**Issue by weibo785424079** [mozilla/pdf.js#13130]
Attach (recommended) or Link to PDF file here:  [test.pdf](https://akmer.aikucun.com/a94a8fe5ccb19ba61c4c0873d391e987982fbbd3_1616477914120_83.pdf)

Configuration:
- Web browser and its version: chrome 87.0.4280.88
- Operating system and its version: windows10
- PDF.js version: 2.6.347
- Is a browser extension:

Steps to reproduce the problem:
1. just open 

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/17724610/112087066-473f8f80-8bc8-11eb-8efb-56139ec42a9c.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by cetinsert** [comment]
first page renders fine; other pages fail on fonts

**Comment by calixteman** [comment]
It's weird: when I read the file with firefox nightly using the above url I've the same issue.
But if I use `qpdf --stream-data=uncompress a94a8fe5ccb19ba61c4c0873d391e987982fbbd3_1616477914120_83.pdf foo.pdf` and then open `foo.pdf` the fonts are rendered correctly.
So probably something is wrong with the stream decompression.

**Comment by calixteman** [comment]
I think I understand the issue.
In a compressed stream we get object numbers and we just check that we've an offset in stream:
https://github.com/mozilla/pdf.js/blob/ba76dd4000c0efa570558dd56d551b773bb4e856/src/core/obj.js#L2168
but this offset is unused.
And then we get the objects:
https://github.com/mozilla/pdf.js/blob/ba76dd4000c0efa570558dd56d551b773bb4e856/src/core/obj.js#L2179
but here some objects should be skipped thanks to the offset.
For example:
```
qpdf --show-object=87,0 foo.pdf
<< /BaseFont /#cb#ce#cc#e5 /DescendantFonts [ 88 0 R ] /Encoding /GBK-EUC-H /Name /FSec_song /Subtype /Type0 /Type /Font >>
```
offset in stream for 87 is 7566
next entry is 105 at offset 7952
```
qpdf --show-object=105,0 foo.pdf
<< /Ascent 1125 /AvgWidth 500 /CIDSet 106 0 R /CapHeight 1125 /Descent -313 /Flags 14 /FontBBox [ -165 -313 1202 1125 ] /FontFile2 107 0 R /FontName /YWYCMW+E-FZ /ItalicAngle 0 /StemV 86 /Style << /Panose <0a0703000509000000000000> >> /Type /FontDescriptor >>
```

but in the stream there is an extra object between 87 & 105:
```
<< /ExtGState << /GSSec_80 32 0 R >> /Font << /F44 33 0 R /F45 40 0 R /F46 47 0 R /F47 52 0 R /F48 58 0 R /F49 63 0 R /F50 69 0 R /F51 76 0 R /F52 81 0 R /FSec_song 87 0 R >> /ProcSet [/PDF /Text /ImageC /ImageB /ImageI] /XObject << /Im2 90 0 R /Im33 91 0 R >> >>
```
and so this one is seen as object 105.

So the fix is to take into account the offset.
@timvandermeij, @Snuffleupagus do you know if we don't use the offset on purpose or if it's just a mistake ?

**Comment by calixteman** [comment]
Specs say that the `N` objects must follow the list of pairs `(number, offset)`:
https://www.adobe.com/content/dam/acom/en/devnet/pdf/pdfs/PDF32000_2008.pdf#page=54
So I guess this pdf is not conform but there are no issues neither in Chrome nor in Evince.

**Comment by calixteman** [comment]
In poppler:
https://gitlab.freedesktop.org/d1saster/poppler/-/blob/848091f4568436cab321ec4571f5f45833692c0f/poppler/XRef.cc#L197-202
the length of the stream used to get the object is set thanks to the offsets and then the stream is consumed until its and so the extra object is skipped.

**Comment by Snuffleupagus** [comment]
> do you know if we don't use the offset on purpose or if it's just a mistake?

Well, in the *ten years* history of this project, this is (to the best of my knowledge) the *first* time that we've seen this kind of error. Hence it's safe to say that it's a) extremely uncommon, and b) suggests that this particular PDF document has a corrupt XRef-stream.

Based on my experience fixing bugs in the XRef-parsing code, you always need to be very careful since it's too easy to fix one thing and break (loads of) others; don't ask me how I know that :-)
At this point in time we should *hopefully* have decent test-coverage of the XRref-code, but I'd highly recommend running *all* tests locally when writing the patch.

**Comment by timvandermeij** [comment]
Fixed by the PR above. Thank you for reporting this!

**Comment by cetinsert** [comment]
There are still missing parts. Here is page 2 of the attached document:

| `.js` `2.8.335` | `ium` `4505` |
|-|-|
| ![image](https://user-images.githubusercontent.com/27027/120944195-27068200-c76e-11eb-9571-5d3ff68afdb8.png) | ![image](https://user-images.githubusercontent.com/27027/120944204-2bcb3600-c76e-11eb-8d10-6e6119873ea7.png) |
