### ISSUE TITLE
Legacy build is incompatible with Chrome 91

### ISSUE THREAD

**Issue by BryanPierce** [mozilla/pdf.js#15411]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: 90.0.4430.0
- Operating system and its version: macOS 12.5.1
- PDF.js version: 2.16.105
- Is a browser extension: No

Steps to reproduce the problem:
1. Use pdfjs legacy build in Chrome 91 or older 

What is the expected behavior? (add screenshot)
No error

What went wrong? (add screenshot)
Errors such as `e.split("+").at is not a function.` occur.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

The `Array.prototype.at()` method (present in the legacy build) was added in Chrome 92, according to this https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/at. Chrome 91 seems like a version that should be supported by the "legacy" build. Indeed, the FAQ states that Chrome 76+ is supported by the legacy build (https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support). At a minimum, the FAQ should be updated if only Chrome 92+ is supported by the latest legacy build.

**Comment by Snuffleupagus** [comment]
The `legacy`-build includes a `Array.prototype.at` polyfill since PR #15008, which was included already in PDF.js `2.15.349` hence this really should be working as-is.

Furthermore, given the difficulty in downloading old Google Chrome releases I've settled for [testing a Chromium build](https://chromium.cypress.io/win64/stable/90.0.4430.212) instead together with [this PDF.js release](https://github.com/mozilla/pdf.js/releases/download/v2.16.105/pdfjs-2.16.105-legacy-dist.zip).
Running a server, and then loading the default viewer, everything works just fine given the polyfill that we bundle in the `legacy` build; with the caveat that I'm testing on Windows (since I don't use MacOS) but I can't imagine that it matters here.

Are you absolutely certain that you actually downloaded a `legacy`-build of the PDF.js library, since the "normal" build only supports the very latest browsers?
Could you perhaps attach the `pdf.js` file, from the build you're using, here so that we can confirm that it's indeed the correct version?

**Comment by BryanPierce** [comment]
I didn't realize the polyfill was there. Thank you for pointing that out. I am using the pdfjs-dist npm package and the legacy build within it. It appears that this is actually a webpack issue or misconfiguration, and I have verified that it works when bypassing webpack. My apologies for wasting your time.

**Comment by LucasBourgeois** [comment]
@Snuffleupagus Alright, I just removed and readded the pdf-dist package and reading the legacy build and I still have arr.at(i) occurences.
Also, when im looking for the polyfill in compatibility.js file, Ive juste nothing in it but a require to isNode.js
![image](https://user-images.githubusercontent.com/18696528/190342816-75967d99-b3a2-41fe-9ab2-7b36fc26828b.png)
![image](https://user-images.githubusercontent.com/18696528/190342879-3014f515-f5bb-4971-a625-b34cef2523f1.png)

My node version is v16.12

**And im just figuring out right now that Im using the https://github.com/mozilla/pdfjs-dist repository and not the pdf.js repository !**

Well, for my problem, im going to use the pdf.js repository and build it with my webpack configuration.
But is it possible that there is an issue with the prebuilt repo ?
