### ISSUE TITLE
Form Field with date format is handled incorrectly for different browsers.

### ISSUE THREAD

**Issue by AlexKay34** [mozilla/pdf.js#15490]
Attach (recommended) or Link to PDF file here:
[PDF mit Datum_edit.pdf](https://github.com/mozilla/pdf.js/files/9622672/PDF.mit.Datum_edit.pdf)

Configuration:
- Web browser and its version: Chrome Version 105.0.5195.127 (Offizieller Build) (64-Bit) / Firefox 105.0 (64-Bit)
- Operating system and its version: Windows 11 Pro 21H2 (German de-DE)
- PDF.js version: v2.16.105
- Is a browser extension: no
- PDF is in en-EN, but same behaviour for de-DE (or de-AT, which was the original problem)

Steps to reproduce the problem in **Chrome**:
1. Open attached PDF with PDFjs in Chrome
2. Enter a date into a date field (e.g. field labeled "von") in the format "d.M.yyyy" (e.g. skipping the leading zero from 01.09.2022 -> 1.9.2022)
3. Click out of the Field to lose focus
4. Date is displayed in format "MM.dd.yyyy"

What is the expected behavior? (add screenshot)
Date is displayed in original format OR date is displayed in "dd.MM.yyyy" format OR an error is shown in the browser stating the format is invalid

Steps to reproduce the problem in **Firefox**:
1. Open attached PDF with PDFjs in Firefox
2. Enter a date into a date field (e.g. field labeled "von") in the format "d.M.yyyy"
3. Click out of the Field to lose focus
4. An Error is shown in the browser stating the format is invalid.

What is the expected behavior? (add screenshot)
Date is displayed in original format OR date is displayed in "dd.MM.yyyy" format OR an error is shown in the browser stating the format is invalid

What went wrong? (add screenshot)
As far as I can tell, the browsers support different date Formats when parsing a string to a date. 
With chrome the date beeing swapped can easily be overlooked. 
Entering "1.9.2022" in a date field and instead of the 1st of september you get the 9th of january can be fatal.

**Comment by Snuffleupagus** [comment]
> As far as I can tell, the browsers support different date Formats when parsing a string to a date.

Yes, and the problem is that browsers themselves don't fully agree on how to parse `Date`-strings since this (as far as I understand) isn't fully specified. Unfortunately this doesn't really looks fixable here, since it's a browser bug in Google Chrome, and it also seems for work as expected in Mozilla Firefox (which is the primary development target for this library).

**Comment by AlexKay34** [comment]
Is there not any way to add another format or parse it differently? 
I found https://momentjs.com/docs/#/parsing/string-format/ which seems like it can handle single digit as day or month

**Comment by calixteman** [comment]
The expected formats are really `dd.MM.yyyy`:
![image](https://user-images.githubusercontent.com/5641725/191686110-4f3c9cc3-820c-463e-9d78-a3bd83601558.png)

I'd have said "just change it to `d.M.yyyy`" but in testing in either Chrome or Acrobat `1.9.2022` is accepted... I don't really understand what's the point of having a format and not respecting it...

**Comment by calixteman** [comment]
In the mentioned PR, I fixed the date parsing to be more permissive with errors: it works like this in Acrobat.
But when pdf.js is used in Chrome, we rely on the `Date.parse` function from Chrome itself and in Chrome `Date.parse("1.9.2021")` corresponds to the 9th of January...
It's almost impossible to fix except in writing our own date parser....
Maybe it's an issue in Chrome.... or a locale setting issue, I don't know.
As @Snuffleupagus mentioned it, there no specs on what `Date.parse` can take.

**Comment by AlexKay34** [comment]
Well, seems like this is not an easy topic. I thought since the displayed date (for this pdf) is always in the "dd.MM.yyyy" format, it might be possible to somehow get this information and parse accordingly even with a not usually supported date format. At least it would seem more likely to be correct than automatically changing to "MM.dd.yyyy" format. However I don't really know much about PDFs and how they work so this is just an assumption.

**Comment by kuntergunt** [comment]
Although this topic might be related to pdf.js it is still not solved today. 
I am having issues at a customer and it was hard to make them understand that the topic is caused by Firefox
Tested with Firefox 126.0.1.

**Comment by deesejohn** [comment]
I'm still seeing this error in German locale. The error is also in English, not German. FF version: 139.0.4

![Image](https://github.com/user-attachments/assets/4d5f97e9-e343-496f-963a-94a0b274db1a)

@Snuffleupagus  @calixteman can this be re-opened?

**Comment by calixteman** [comment]
It seems that I didn't test my patch correctly..
I don't really understand why you don't want to respect the date format which is hardcoded in the PDF itself and the alert dialog shows you the right format to use.

Maybe we could consider that's a bug in Acrobat... instead of considering that's a bug in pdf.js...
Anyway, I'll try to fix this issue, but my concern is that if we try to do some magic and we're wrong in our guess, then the user won't have any way to know what's the expected format (especially if it's "exotic"), that said maybe we could display the expected format as a tooltip on the field.

**Comment by deesejohn** [comment]
>I don't really understand why you don't want to respect the date format which is hardcoded in the PDF itself and the alert dialog shows you the right format to use.

I have no clue what `dd. mmmm yyyy` would look like. I tried `01. Janu 2025` but it didn't work. I would expect `01.01.2025` for DE date format. I'd honestly rather just have the ability to toggle off validation (either completely or the field level).
