### ISSUE TITLE
pdf files cannot be previewed

### ISSUE THREAD

**Issue by cuuc20072008** [mozilla/pdf.js#16098]
If you have time, please take a look at the problem that the file cannot be previewed normally, thank you.
![image](https://user-images.githubusercontent.com/37201595/221765005-ae04e3d9-5101-4f94-b4c8-0274a30ca129.png)
[金斧子集团简介（10周年版）.pdf](https://github.com/mozilla/pdf.js/files/10846993/10.pdf)

**Comment by rakshith2001** [comment]
is the issue solved?

**Comment by calixteman** [comment]
> is the issue solved?

Did you see something which indicates that this issue is solved ??
Please use this bug tracker to bring useful information.
If you think that we aren't fast enough, please feel free to write a patch and make a PR, useful contributions are very welcome.

**Comment by cuuc20072008** [comment]
> > is the issue solved?
> 
> Did you see something which indicates that this issue is solved ?? Please use this bug tracker to bring useful information. If you think that we aren't fast enough, please feel free to write a patch and make a PR, useful contributions are very welcome.

I still can't open the PDF correctly. The following is what I opened and displayed on the computer software. Is it a font problem? Do I need to install new fonts into my font library?

![image](https://user-images.githubusercontent.com/37201595/227915270-02392a18-cb0b-41f8-9947-f5abda7f28fe.png)

**Comment by calixteman** [comment]
The rendering on Mac 13.3.1 (M1) in Acrobat and in Firefox is the same.
Some glyphs have their charstring equal to `[1, 1, ...]`(`1 == hstem`) which doesn't make sense and explain why OTS is complaining.
I used `ttx`with `GGRCZV+SourceHanSansCN-Normal` and the file is huge but a quick look gave me the impress that charstrings are almost only garbage.
But the rendering is ok in either Preview or in Chrome...
