### ISSUE TITLE
After update on 6.23.2023 PDF is downloaded instead of shown in embed tag area

### ISSUE THREAD

**Issue by BuddhaBuddy1** [mozilla/pdf.js#16594]
Attach (recommended) or Link to PDF file here: Any PDF file

Configuration:
- Web browser and its version: Chrome Desktop Version 114.0.5735.134 (Official Build) (64-bit)
- Operating system and its version: Windows 10 22H2
- PDF.js version: 3.7.108
- Is a browser extension: Yes

Steps to reproduce the problem:
1. Visit webpage with embed tag like this:
    `<embed src="/relative/path/[docId]?name=test.pdf" width="1598" height="981" type="application/pdf">`
2. On click of a row in a table, update embed link with correct info and reload the div

What is the expected behavior? Document shown in embed tag area

What went wrong? Document downloaded instead

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
https://chrome.google.com/webstore/detail/pdf-viewer/oemmndcbldboiebfnladdacbdfmadadm

**Comment by Rob--W** [comment]
Could you show an actual example that reproduces the issue? I've tested https://robwu.nl/pdfjs/object-embed.html before publication, which among other things loads PDF in `<embed src="file.pdf" ... type="application/pdf">`, and that works just fine.

**Comment by Snuffleupagus** [comment]
Was this perhaps fixed by PR #16612?

**Comment by BuddhaBuddy1** [comment]
@Rob--W Thanks for that link. The embed tags there work for me, too, but our page still doesn't seem to work. The difference is that we don't have the page embedded in the link at render time. We create the embed tag via javascript when someone clicks on a link in a list.

@Snuffleupagus I'm using PDF Viewer from here (https://chrome.google.com/webstore/detail/pdf-viewer/oemmndcbldboiebfnladdacbdfmadadm), which was updated yesterday. I assume it has the fix you mention.

**Comment by Rob--W** [comment]
Is the issue still happening with the latest version? If yes, can you share a test case? Without it this I cannot investigate nor fix the issue.

**Comment by BuddhaBuddy1** [comment]
I don't know if there was a second update of the PDF Viewer library or not, but it is now working on our page!

**Comment by Rob--W** [comment]
There has indeed been an update (https://github.com/Rob--W/pdf.js/releases/tag/chrome-3.9.49). Based on the description your issue was most likely resolved by https://github.com/mozilla/pdf.js/pull/16612

Thanks for reporting and confirming that the issue is gone!
