### ISSUE TITLE
Concurrent render requests result in content not being rendered

### ISSUE THREAD

**Issue by AntonioCandinho** [mozilla/pdf.js#16617]
Attach (recommended) or Link to PDF file here:
- https://raw.githubusercontent.com/fjtrujy/wasm-max-ram/d50f1524f93e105c0a29ddcf07e6aaa5a7fecb84/3.pdf

Configuration:

- Web browser and its version: Google Chrome Version 114.0.5735.133 
- Operating system and its version: MacOS Ventura 13.3.1
- PDF.js version: 3.7.107
- Is a browser extension: No

Steps to reproduce the problem:

By using the same `pdfJS.getDocument()`, issue multiple concurrent render page requests and wait for them to complete (`Promise.all`). Some of them will result in not rendered content.  It can be reproduced using the following snippet:

```javascript
import * as pdfJS from 'pdfjs-dist';

pdfJS.GlobalWorkerOptions.workerPort = new Worker(new URL(window.location.origin + '/pdf.worker.js'));

const DocumentURL = `${window.location.origin}/bad_doc.pdf`;

const renderPDF = async (container, page) => {
  const viewport = page.getViewport({ scale: 1.0 });

  const canvas = document.createElement('canvas');
  const context = canvas.getContext('2d');
  canvas.height = viewport.height;
  canvas.width = viewport.width;

  const renderContext = { canvasContext: context, viewport: viewport };
  const renderTask = page.render(renderContext);

  await renderTask.promise;

  container.appendChild(canvas);
};

const main = async () => {
  const container = document.getElementById('app');
  const pdfDoc = await pdfJS.getDocument(DocumentURL).promise;
  const page = await pdfDoc.getPage(1);
  const renderRequests = [];
  for (let i = 0; i < 40; i++) {
    renderRequests.push(renderPDF(container, page));
  }
  await Promise.all(renderRequests);
};

main();
```

What is the expected behavior? (add screenshot)

Issuing multiple rendered requests at the same time should result in all of them being correctly rendered. 

<img src="https://github.com/mozilla/pdf.js/assets/9798193/34cd81a3-50a9-4e47-b864-b69f38af3bb7" width="400"/>

What went wrong? (add screenshot)

For some documents, rendering pdfs at the same time results in some of them not being rendered. 

<img src="https://github.com/mozilla/pdf.js/assets/9798193/cbbe627e-9b2c-4352-ad9b-7323c5b9a287" width="400" />

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

- https://stackblitz.com/edit/vitejs-vite-wevrsz?file=public%2Fpdf.worker.js

**Comment by Snuffleupagus** [comment]
It's possible that was fixed by PR #16551, so please re-test this using (the just released) PDF.js version `3.8.162`.

**Comment by AntonioCandinho** [comment]
> It's possible that this was fixed by PR https://github.com/mozilla/pdf.js/pull/16551, so please re-test this using (the just released) PDF.js version 3.8.162.

HI @Snuffleupagus! I've updated the Stackblitz playground with that version, but I'm afraid the error is still happening 😅

**Comment by Snuffleupagus** [comment]
> I've updated the Stackblitz playground with that version, but I'm afraid the error is still happening

The example at https://stackblitz.com/edit/vitejs-vite-wevrsz?file=public%2Fpdf.worker.js is now completely broken, and looking at the console the following Error is printed `The API version "3.8.162" does not match the Worker version "3.7.107".`, hence it seems that you didn't actually update the `pdf.worker.js` file (but only editing your `package.json` file).

**Comment by AntonioCandinho** [comment]
Sorry, I must have done something wrong when updating the library. The example seems to be working now with `3.8.162`. I will close this issue; thank you for your time.
