### ISSUE TITLE
Global 'keydown' event listener for the AnnotationEditorUIManager hijacks keystrokes.

### ISSUE THREAD

**Issue by atrinker** [mozilla/pdf.js#17167]
Attach (recommended) or Link to PDF file here: Any PDF will work

Configuration:
- Web browser and its version: Tested on multiple browsers, including Firefox v118.0.2 and Electron v24.4.0
- Operating system and its version: Windows 10
- PDF.js version: v3.11.174

Steps to reproduce the problem:
1.  Navigate to https://codesandbox.io/s/pdfjs-dist-with-ts-forked-4jczx7?file=/src/index.ts
2.  Upload PDF
3.  Type in the textbox (note that deleting with backspace or DEL key works at this point)
4.  Press "Toggle Highlight" button (which toggles the viewer to between "NONE" and "INK" annotation modes)
5.  Attempt to Delete text in input field using either backspace or DEL keys.

What is the expected behavior? (add screenshot)

You should be able to delete text from the input field, ideally when the focus leaves the pdf viewer container for another element, but at the least when the annotationEditorMode for the viewer is set to NONE.

What went wrong? (add screenshot)

Backspace and DEL keys no longer function once highlighting is toggled on, even if it is later toggled off.
Keydown event listener in src/display/editor/tools.js is hijacking the DEL and backspace keys, even after the annotationEditoMode for the viewer is set to NONE. 

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
https://codesandbox.io/s/pdfjs-dist-with-ts-forked-4jczx7?file=/src/index.ts

**Comment by Snuffleupagus** [comment]
> You should be able to delete text from the input field, ideally when the focus leaves the pdf viewer container for another element

This part can be reproduced in the default viewer, with the pageNumber-input while editing is active.
@calixteman Is this something that we want to try and address?

**Comment by calixteman** [comment]
I managed to reproduce with the page number input too, so we should fix it.

**Comment by atrinker** [comment]
Thanks for all your work on this!  I've noticed that this issue still exists for non-<input> elements, such as a <div> with contenteditable set to true.

See: https://codesandbox.io/p/sandbox/pdfjs-dist-with-ts-forked-snjhjf?file=%2Findex.html%3A19%2C28.

Would you like me to open a new issue for this, or would it make more sense to re-open this issue?
