### ISSUE TITLE
Printing a PDF file, adds an extra blank page at the end

### ISSUE THREAD

**Issue by frapell** [mozilla/pdf.js#4041]
When printing a PDF file using the PDF.js viewer, it will come with an extra blank page at the end.

Steps to reproduce:

1) Go to the PDF.js demo page
2) Open a test file with 2 pages (you can use this one http://www.filedropper.com/test_20 )
3) Click print, and either print to a file, or print with a printer

The result will be pages 1 and 2 correct, and an extra blank third page

**Comment by clone1018** [comment]
We're also experiencing this issue.

**Comment by filipecmartins** [comment]
Hi,

I'm also experiencing this issue.

Any clue?

**Comment by jsonn** [comment]
I'm seeing this as well. Online example for me is http://www.fpdf.org/en/script/ex36.pdf.
Modifying the document by hand to reduce the media box to a height of at most 841pt makes it work. This makes me wonder where the 1pt is getting lost...

**Comment by Rob--W** [comment]
Confirmed the bug of @jsonn in Firefox. It does not happen with the PDF.js viewer in Chrome.

**Comment by shaunfreeman** [comment]
I can confirm that this is still happening in 43.0.4. 
A workaround I did to stop this was to make my A4 PDFs have a height of 841pt.
The  official dimensions of A4 are 8.27in x 11.69in, which actually comes to 595.44pt x 841.68pt

**Comment by timvandermeij** [comment]
Closing as fixed by #7005.

**Comment by giordy** [comment]
The problem is still present in Firefox 48 on Fedora 24 x86_64.

- If I print a PDF containing 1 page only, at the end the printer outputs one extra white page.
- If I ask for 2 copies of a PDF containing 1 page only, I get 1 white page at the end of the first copy and 1 white page at the end of the second copy.

**Comment by jsonn** [comment]
The problem is indeed fixed in pdf.js, but for whatever reason, the copy in Firefox is outdated.

**Comment by infosecliqin** [comment]
> 当使用PDF.js查看器打印PDF文件时，它的末尾会有一个空白页。
> 
> 重现步骤：
> 
> 1. 转到PDF.js演示页面
> 2. 打开一个包含2页的测试文件（您可以使用一个http://www.filedropper.com/test_20）
> 3. 单击打印，然后打印到文件或使用打印机打印
> 
> 结果将是正确的第1页和第2页，以及额外的空白第三页

您好，请问解决了吗？？？有什么方式呢
