### ISSUE TITLE
Tracemonkey is not rendering perfectly

### ISSUE THREAD

**Issue by timvandermeij** [mozilla/pdf.js#4985]
- [x] Image on page 2 is not rendering properly.
- [x] Image on page 11 misses color and gradients.
- [ ] Image on page 13 misses some lines and fills.
- [x] The console also complains about some other missing operations.

**Comment by terurou** [comment]
Fixed page 11 issue by #10646.

**Comment by timvandermeij** [comment]
The rendering of page 13 is improved by the pull request above, but it's not entirely fixed yet.
