### ISSUE TITLE
Feature Request: Support hyperlinks in Document Outline

### ISSUE THREAD

**Issue by nibblesnbits** [mozilla/pdf.js#5089]
Some PDFs I'm displaying with the viewer contain items in the document outline that, when rendered in Adobe Reader (haven't checked others), are actually hyperlinks.  Would it be possible to support this in pdf.js?  I'm looking at `readDocumentOutline` in `obj.js` right now and found what will hopefully lead me in the right direction, but if I'm off track let me know and I'll see if I can make the changes myself.

**Comment by kvk123456** [comment]
is there any fix for this issue in next available release?

**Comment by timvandermeij** [comment]
(Related to #3214)

**Comment by kvk123456** [comment]
Since 3214 also closed can someone please answer me 

Any resolution for this? can you please let us know the hyperlink issue in bookmark will be fixed in next release?

**Comment by Snuffleupagus** [comment]
I'm attaching the PDF file from issue #3214 here, as an additional example: [bookmark-unsupported-features.pdf](https://github.com/mozilla/pdf.js/files/69030/bookmark-unsupported-features.pdf).

**Comment by timvandermeij** [comment]
@kvk123456 As far as I know nobody is working on this. If someone would like to fix this, feel free to submit a pull request. We are just closing the other issues because they are duplicates of this one.

**Comment by kvk123456** [comment]
Thanks timvandermeij, here is the link I reported in 6788.

https://fbutools-stage.rightmix.com/Viewer.aspx?file=%2fViewer%2fHosted%2fGetDocument.ashx%3ffile%3dhttp%3a%2f%2fstage.efinancialdocs.com%2fdocuments%2fDocData%2fFBU2001_DOC_S_201532112645_FBU2001_LOAD.PDF

**Comment by Rob--W** [comment]
FYI, I developed a patch (not published) that recovers a missing outlune from marked content (#6269). It does not work for many documents (because marked content is not that common), so I stopped working on it.

**Comment by Snuffleupagus** [comment]
Here's a quick, sort of hacky, patch that adds basic support for URLs in the outline (I don't know if it's in good enough shape to bother with submitting a PR): https://github.com/Snuffleupagus/pdf.js/commit/c7d3060a614978aea6c2db04a6a6b75547613186.

**Comment by kvk123456** [comment]
when is the next release, whiich will have this fix?

**Comment by gsampath127** [comment]
The code is working when we the open pdf from local system.
When the pdf document is opened as query string to the viewer. The issue still exists.
Please suggest any better solution for this.

http://rightprospectus-stage.rightprospectus.com/documents/BlackRock/SUM_AllCapEnergyResourcesPortfolioServiceShares.pdf

**Comment by gsampath127** [comment]
Can someone please respond here . Is the issue is fixed if in which version.

var dest = outlineDict.get('A');
if (dest) {
    if (dest.has('URI')) {
        dest = dest.get('URI');
    } else {
        dest = dest.get('D');
    }

The code is working when we the open pdf from local system.
When the pdf document is opened as query string to the viewer. The issue still exists.

http://rightprospectus-stage.rightprospectus.com/documents/BlackRock/SUM_AllCapEnergyResourcesPortfolioServiceShares.pdf

**Comment by timvandermeij** [comment]
We have pull request #6822 to implement this, though the review for it needs to be completed. It is not fixed yet, otherwise this issue would have been closed.

**Comment by timvandermeij** [comment]
Closing as fixed by #6822. URLs in document outlines are now supported. The other outline issues are tracked in #3214.

**Comment by creage** [comment]
I have an example [PDF document with bookmarks](https://drive.google.com/file/d/0B-SWFrRb1dsMVmVxNmx1eG5vcDA). Adobe navigates by them fine, but viewer does not. Exploring the DOM of the document outline displays empty **href** attributes

![image](https://user-images.githubusercontent.com/910967/29708734-0a5e2804-898a-11e7-822b-a690149730fd.png)

**Comment by Snuffleupagus** [comment]
@creage Next time, please open a *new* issue rather than commenting on a old and already fixed one!
Furthermore, note that your PDF file is actually not valid according to the specification, since the outline data isn't entirely correct.
