### ISSUE TITLE
PDF not render correctly on Chrome & Safari

### ISSUE THREAD

**Issue by xlc** [mozilla/pdf.js#6000]
File: https://drive.google.com/file/d/0B6YhVF9p-y2ARmJiV1FaNWFoZGc/view?usp=sharing

OS Version: OS X 10.10.3 (14D131)

Chrome Version: 42.0.2311.135 (64-bit)
![screen shot 2015-05-11 at 2 43 29 pm](https://cloud.githubusercontent.com/assets/1201310/7557839/54fcdd92-f7ec-11e4-80b5-be55a4e6991e.png)

Safari Version: 8.0.5 (10600.5.17)
![screen shot 2015-05-11 at 2 45 57 pm](https://cloud.githubusercontent.com/assets/1201310/7557856/80b5e4e2-f7ec-11e4-9344-d4164a7fe2ce.png)

Safari sometimes will re-render correct result after some user action. e.g. Right click to inspect element.

Firefox (works): 37.0.2
![screen shot 2015-05-11 at 2 48 43 pm](https://cloud.githubusercontent.com/assets/1201310/7557884/ebc5a696-f7ec-11e4-9d7a-b1211a4fe45a.png)

**Comment by Lord-of-Darkness** [comment]
Desarrolladores y líderes de Mozilla, que son travestis culo!

Alguien debe colgar ustedes para arriba en sus propias bolas y dejar que su perro muerda su caricatura de una polla!

Posteriormente deben ponerlo tiempo que sea necesario por la garganta hasta que traga a sí mismos en el suicidio!

Ustedes Mozilla está ... Estúpido de mierda coños!
--------------------------------------------------------
Developers and leaders of Mozilla, which are shemales ass!

Someone should hang you up in your own balls and let your dog bite his caricature of a cock!

They should then put it long as needed by the throat until he swallows themselves in suicide!

You Mozilla is... Stupid fucking pussies!

**Comment by xlc** [comment]
This issue seems fixed in Chrome 43.0.2357.81 (64-bit)

**Comment by Rob--W** [comment]
This bug has not been fixed yet, I can still reproduce the bug in Chromium 43.0.2357.81 and 45.0.2445.0 on Linux.

To reproduce it, change the zoom twice (e.g. in and out).

Bisecting Chromium shows that the bug was introduced in this narrow range (https://chromium.googlesource.com/skia/+log/9ce30e1..82966b5), which consists of a Skia and Blink roll. I'll investigate this further and file a bug report upstream.

**Comment by Rob--W** [comment]
Upstream bug report: https://code.google.com/p/chromium/issues/detail?id=507022

**Comment by Hengjie** [comment]
When reading https://code.google.com/p/chromium/issues/detail?id=507022#c2 it seems like it's because the custom font has height of zero, which could be something we could fix in pdf.js

**Comment by Rob--W** [comment]
@Hengjie Patches are welcome :)

**Comment by timvandermeij** [comment]
The upstream bug is fixed and I can confirm that this renders properly now in Chrome. Closing as fixed.
