### ISSUE TITLE
Chrome browser is not supported very well.

### ISSUE THREAD

**Issue by qingzhengzhuma** [mozilla/pdf.js#6306]
When I use PDF.js open a chinese document in chrome, part of contents in some pages are missed. the console tells "The provided value 'moz-chunked-arraybuffer' is not a valid enum value of interface XMLHttpRequestResponseType."(webL10n/l10n.js,L829) and "The provided value 'moz-chunked-arraybuffer' is not a valid enum value of interface XMLHttpRequestResponseType."(pdf.worker.js,L1649), the chrome version is 43.0.2357.132.

**Comment by CodingFabian** [comment]
This should have been fixed by #5531 are you using a pdf.js newer than that?

**Comment by xlc** [comment]
I can conform the `moz-chunked-arraybuffer` warning is happening on the demo viewer on Chrome 44.0.2403.125 OS X 10.10.4
> pdf.worker.js:1649 The provided value 'moz-chunked-arraybuffer' is not a valid enum value of type XMLHttpRequestResponseType.

However it is merely a warning Chrome display during feature detection and doesn't indicate any sort of error.

**Comment by existentialism** [comment]
@CodingFabian the feature detection bit still occurs if `MINIFIED` or `GENERIC` build targets are used

**Comment by nschloe** [comment]
Waity, why this is closed? I'm still getting the warning
```
The provided value 'moz-chunked-arraybuffer' is not a valid enum value of type XMLHttpRequestResponseType.
```
on Chrome  44.0.2403.130 (64-bit) with pdf.js 1.1.377.

**Comment by yurydelendik** [comment]
> Waity, why this is closed? 

See #5531

**Comment by nschloe** [comment]
I'm using pdf.js-dist 1.1.377 and still get this warning. I'll debug this in a bit.

**Comment by yurydelendik** [comment]
You will get the warning but only once -- it will feature test ability to load data in chunks.

**Comment by nschloe** [comment]
I understand. I guess it's all working as expected then, and everyone can ignore the warning. It's really quite funny though that there should be one.

**Comment by qingzhengzhuma** [comment]
There seems to be a lot to discuss, I reopen it. Sorry about what I've done.

**Comment by nschloe** [comment]
@qingzhengzhuma I think it's fine to close this issue. We still have a warning here (which I would consider an issue indeed), but we're looking at https://github.com/mozilla/pdf.js/issues/6126#issuecomment-130462101 as a possible fix, we can discuss everything over there.

**Comment by lenichols** [comment]
Any updates on this warning? im still getting it...

**Comment by Rob--W** [comment]
@lenichols This was fixed in #5531. Which version of PDF.js are you using?

**Comment by sand0oo** [comment]
I am using Pre-built v1.3.91 and also getting the warning
I also can see the warning on chrome the demo page http://mozilla.github.io/pdf.js/web/viewer.html

**Comment by Rob--W** [comment]
Ah, that is right. There is no warning in the Chrome extension, because that code is removed during the build. But it is present in a generic build because it is not known upfront Firefox, or some other browser is used. Just ignore that warning.

**Comment by jvanbrug** [comment]
I'm using v1.4.124 of pdf-dist from npm, and the warning `The provided value 'moz-chunked-arraybuffer' is not a valid enum value of type XMLHttpRequestResponseType.` appears in Chrome console every time I render a page. I'm still in the middle of getting my document viewer to work, but I don't think it's related to any problems. I'm just here to whine that it's an annoying message. :weary:

**Comment by avindhawale** [comment]
getting same warning with v1.4.131.....

**Comment by Rob--W** [comment]
@timvandermeij This message seems to bother a lot of people. Should we add a simple conditional check for Chrome (e.g. `!window.chrome && ...`)?

**Comment by timvandermeij** [comment]
@Rob--W I agree that the message is not ideal. We want to avoid browser-specific code in the `src` folder as much as possible, but if there is no other way then I guess we have to go for it. You can always submit a PR and see how other developers think about this.

**Comment by akamustang** [comment]
Working version of @Rob--W's suggestion which prevents the warning.

**pdf.worker.js - line: 8769**
```
- var supportsMozChunked = (function supportsMozChunkedClosure() {
+ var supportsMozChunked = !(typeof navigator !== 'undefined' && /Chrome/.test(navigator.userAgent)) && (function supportsMozChunkedClosure() {
```

**Comment by natcohen** [comment]
I'm still getting this warning... Using chrome 53 and latest pdf.js beta

**Comment by thj-dk** [comment]
Still getting this warning on Chrome v55.0.2883.87

**Comment by ssougnez** [comment]
+1

**Comment by sschafheutle** [comment]
+1

**Comment by Spatlani** [comment]
+1

**Comment by apokyro** [comment]
+1

**Comment by yurydelendik** [comment]
locking the conversation (mostly because of +1's)

**Comment by yurydelendik** [comment]
Addressed by #8768
