### ISSUE TITLE
Extra blank page printed after each page

### ISSUE THREAD

**Issue by beardygeek** [mozilla/pdf.js#6461]
This is currently happening on Firefox 40.0.0, and latest version of Chrome on Windows.
The pdf displays normally in the viewer without any blank pages.  It is only on printing that the extra pages appear.

**Comment by timvandermeij** [comment]
Even with the latest viewer at https://mozilla.github.io/pdf.js/web/viewer.html? I recall this was fixed a while ago. There was an upstream regression in Chrome 45 that has also been fixed for newer versions.

**Comment by beardygeek** [comment]
We have a customised version of viewer.html, but we're using the latest js versions.  Would that fix have been in the viewer.html file?

**Comment by timvandermeij** [comment]
It should have been fixed in #5857. Could you try opening a file that gives you blank pages with https://mozilla.github.io/pdf.js/web/viewer.html (Open File button in the toolbar) to see if the issue is there too?

**Comment by veranz** [comment]
Yes it's still occurring. I'm facing the same issue using the latest version of Chrome Version 45.0.2454.101 m and Version 45.0.2454.99 m. The confusing thing is that i cannot replicate the extra blank page issue using the demo https://mozilla.github.io/pdf.js/web/viewer.html and i can only do so in my project. All others browsers are working fine but somehow Chrome is not. What am i missing?

**Comment by timvandermeij** [comment]
@veranz That is probably due to #6345.

**Comment by beardygeek** [comment]
To update you, we've tested the viewer at https://mozilla.github.io/pdf.js/web/viewer.html, using this file (https://www.dropbox.com/s/6lves3ge8s2u48g/bedcard.pdf?dl=0). It works perfectly in Chrome, and the extra margin issue (https://github.com/mozilla/pdf.js/issues/6462#issuecomment-141939588) is also fixed.

However, in Firefox both these issues are still present.

**Comment by beardygeek** [comment]
Hi, any update on this issue?  Is it in the queue to be fixed/tested?

**Comment by ming300** [comment]
my way:
on viewer.js  file

```
change 
var DEFAULT_SCALE_DELTA = 1.1;

to
var DEFAULT_SCALE_DELTA = 1;
```

**Comment by timvandermeij** [comment]
Closing as fixed by #7005.
