### ISSUE TITLE
Extra margin space added in printed version of pdf

### ISSUE THREAD

**Issue by beardygeek** [mozilla/pdf.js#6462]
PDF.js with Firefox is adding 0.5cm to the left and top margin and shrinking the page elements
PDF.js with Chrome is adding 0.8cm to the top margin - elements are the correct size but are shunted down the page.
Tested on Windows, FF 40.0.

**Comment by timvandermeij** [comment]
Do you have a screenshot? Does it happen with every PDF or just particular ones? In that case, please link one.

**Comment by beardygeek** [comment]
It's not in the display, it's on the final hard copy after printing.

**Comment by lszhu** [comment]
I encountered the bug in old versions (v1.0), but v1.1.215 is ok in chrome (v44)

**Comment by beardygeek** [comment]
To update you, we've tested the viewer at https://mozilla.github.io/pdf.js/web/viewer.html, using this file (https://www.dropbox.com/s/6lves3ge8s2u48g/bedcard.pdf?dl=0).  It works perfectly in Chrome, and the extra page issue (https://github.com/mozilla/pdf.js/issues/6461#issuecomment-141939466) is also fixed.

However, in Firefox both these issues are still present.

**Comment by beardygeek** [comment]
Hi, any update on this issue?  Is it in the queue to be fixed/tested?

**Comment by timvandermeij** [comment]
Closing as fixed by #7005.

**Comment by TomatoJoe** [comment]
I know this is an old thread but this issue is still causing me grief.
We print labels , 4 per sheet this adding anything to the margins of the final print is a critical fault/bug.
Now forced to go with the latest vesion of FF due to continuous addon issues. 
Heres the problem:
FF v52.2.1esr Win 7 : Added ~0.5" to Left and Top margins (possibly R & B also).
FF v67.0 (latest) Win 7 : Added ~0.5" to Left margins 
FF v67.0 MX Linux : No added margins, however cannot use due to another bug with the Linux version of PDF.js .
I have tried/checked:
- Set in about:config , all magins for the printer to 0 (print.printer_4100DN_USB.print_margin_top etc)
- Ensure there are no additional Gutter or Margins added by the Printer properties.
- Ensure the Application adds no add'l margin 
Symptoms:
Preview in Firefox  - No margins added and looks as it should.
Paper printout and Print Preview - Added extra Margin.
We are forced to use the FF Preview in FF because there is no Adobe Acrobat Reader plugin sopport since v57. With the old v52.2.1 FF with Acrobat Plugin everything works perfectly.
