### ISSUE TITLE
Radial gradient with the SVG backend

### ISSUE THREAD

**Issue by benbro** [mozilla/pdf.js#8045]
Link to PDF file:
https://drive.google.com/open?id=0B12AhxvnYHrATm5Tb0VLcjloUWc

Configuration:
- Web browser and its version: Firefox 51.0.1
- Operating system and its version: Windows 7
- PDF.js version: build: "35102c02", version: "1.7.267"
- Is an extension: no

Steps to reproduce the problem:
1.  Set the [viewer](https://mozilla.github.io/pdf.js/web/viewer.html) renderer to SVG with PDFViewerApplication.preferences.set('renderer', 'svg')
2.  Load the PDF

What is the expected behavior? (add screenshot)
![tf00001176-foxit](https://cloud.githubusercontent.com/assets/75841/22742040/07e8dafe-ee1e-11e6-8211-c6d35b25b8d5.png)

What went wrong? (add screenshot)
canvas looks almost correct:
![tf00001176-canvas](https://cloud.githubusercontent.com/assets/75841/22742049/0e23dcca-ee1e-11e6-900a-e0cfc39e01bc.png)
svg show just black background:
![tf00001176-svg](https://cloud.githubusercontent.com/assets/75841/22742054/10ede18a-ee1e-11e6-9479-b0cb06161d0a.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by zacharyShao** [comment]
same issue ,how to fix?

**Comment by benbro** [comment]
@timvandermeij the second image is rendered using the canvas backend so this is not just svg issue.

**Comment by yurydelendik** [comment]
Better test https://github.com/mozilla/pdf.js/blob/master/test/pdfs/gradientfill.pdf

**Comment by terurou** [comment]
Fixed partially by #10646.
Must implement these operators for https://drive.google.com/open?id=0B12AhxvnYHrATm5Tb0VLcjloUWc
> Warning: Unimplemented operator beginGroup
> Warning: Unimplemented operator endGroup
> Warning: Unimplemented graphic state BM
> Warning: Unimplemented graphic state SMask

**Comment by benbro** [comment]
The radial gradient still doesn't look the same as Evince.
[tf00001176.pdf](https://github.com/mozilla/pdf.js/files/9893531/tf00001176.pdf)
