### ISSUE TITLE
Font is broken □□

### ISSUE THREAD

**Issue by fclemonschool** [mozilla/pdf.js#9568]
Attach (recommended) or Link to PDF file here: [pdfjstest.pdf](https://github.com/mozilla/pdf.js/files/1818070/pdfjstest.pdf)

Configuration:
- Web browser and its version: Chrome canary 67.0.3371.0, Firefox developer edition 60.0b3, Edge 41.16299.248.0

- Operating system and its version: Windows 10 Home 1709
- PDF.js version: online demo version 1.9.426
- Is a browser extension: no

Steps to reproduce the problem:
1. open pdf file with online demo
2.

What is the expected behavior? (add screenshot)
![37506089-a0aaa012-292b-11e8-811d-e6e850fe4967](https://user-images.githubusercontent.com/18299676/37572835-72b3ac46-2b54-11e8-87e2-7228d33c380c.png)

What went wrong? (add screenshot)
font is broken, please help me. what i need to do?

at chrome canary
![37506066-8a6267fe-292b-11e8-8e82-5716c6874fb3](https://user-images.githubusercontent.com/18299676/37572825-50c3936c-2b54-11e8-8ae1-0654ad380200.png)

at edge browser
![37506280-7656b32c-292c-11e8-9c7c-b38eec7245ef](https://user-images.githubusercontent.com/18299676/37572838-79d2ec26-2b54-11e8-9ade-a0c6fe4092b7.png)

at firefox
![37506350-c9fe997c-292c-11e8-9dc2-00a70e9827b5](https://user-images.githubusercontent.com/18299676/37572842-804b4a1c-2b54-11e8-9b84-ec34635d5468.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

Maybe this font is problem. This is signed by adobe sign.
![image](https://user-images.githubusercontent.com/18299676/37506407-07cd9186-292d-11e8-9ffb-532f36f7c94e.png)

**Comment by fclemonschool** [comment]
Is pdf.js neglecting font problems? I've read some font-related questions from other people before, and there is no answer.

**Comment by timvandermeij** [comment]
No, we're not. If you check https://github.com/mozilla/pdf.js/pulls?q=label%3A4-font-conversion+is%3Aclosed+is%3Apr amongst others, you'll see that many have been solved before. Note that these issues are usually far from trivial to solve and may therefore take a long time, also because there are not many people that can debug such issues. Please refrain from posting such comments as they're not helpful for solving the problem.

**Comment by DenisVuyka** [comment]
Trying the file with Firefox 62.0b9 and the issue is still there. We experience the similar problem with many documents displayed with the corrupted fonts.

**Comment by timvandermeij** [comment]
Fixed by #9340.
